### ISSUE TITLE
viewControllersToPresent not working

### ISSUE THREAD

**Issue by arianaantonio** [Raizlabs/BoardingPass#14]
This doesn't appear to be working as a way to setup my hierarchy of viewControllers. Adding them as an array does not push them onto the navigation stack.

**Comment by ateliercw** [comment]
`viewControllersToPresent` is used to set the desired flow of view controllers that the `BoardingNavigationController` will show, you should be able to call `setViewControllers(_:,animated:)` to pre-populate the navigation stack.
